import type { Product, Collection } from "./types";

// Real product images from Olha's Blossom Jewellery Art collection
export const mockProducts: Product[] = [
  // === UKRAINIAN HERITAGE ===
  {
    _id: "ukr-1",
    name: "Vyshyvanka Lavender Earrings",
    slug: { current: "vyshyvanka-lavender-earrings" },
    description: [],
    price: 35,
    images: [],
    imageUrl: "/images/products/ukrainian-heritage/lavender-vyshyvanka-earrings.jpg",
    inStock: true,
    featured: true,
    materials: ["Polymer Clay", "Sterling Silver Hooks", "Pearl Beads"],
    dimensions: "4cm drop length, 2.5cm diameter",
    careInstructions: "Avoid water contact. Store in provided box away from direct sunlight.",
    collection: { _id: "col-1", name: "Ukrainian Heritage", slug: { current: "ukrainian-heritage" } },
  },
  {
    _id: "ukr-2",
    name: "Red Folk Cross-Stitch Earrings",
    slug: { current: "red-folk-cross-stitch-earrings" },
    description: [],
    price: 35,
    compareAtPrice: 45,
    images: [],
    imageUrl: "/images/products/ukrainian-heritage/red-folk-earrings.jpg",
    inStock: true,
    featured: true,
    materials: ["Polymer Clay", "Sterling Silver Hooks", "Red Crystal Beads"],
    dimensions: "5cm drop length, 2.5cm per disc",
    careInstructions: "Avoid water contact. Store in provided box away from direct sunlight.",
    collection: { _id: "col-1", name: "Ukrainian Heritage", slug: { current: "ukrainian-heritage" } },
  },
  {
    _id: "ukr-3",
    name: "Poppy & Sunflower Necklace Set",
    slug: { current: "poppy-sunflower-necklace-set" },
    description: [],
    price: 85,
    images: [],
    imageUrl: "/images/products/ukrainian-heritage/poppy-sunflower-set.jpg",
    inStock: true,
    featured: true,
    materials: ["Polymer Clay", "Sterling Silver Chain", "Crystal Beads", "Natural Stones"],
    dimensions: "Necklace: 42cm chain + 5cm extension. Earrings: 3cm drop",
    careInstructions: "Handle with care. Each flower is sculpted by hand. Store flat in box.",
    collection: { _id: "col-1", name: "Ukrainian Heritage", slug: { current: "ukrainian-heritage" } },
  },

  // === YELLOW ROSES ===
  {
    _id: "yr-1",
    name: "Yellow Rose Complete Set",
    slug: { current: "yellow-rose-complete-set" },
    description: [],
    price: 95,
    compareAtPrice: 120,
    images: [],
    imageUrl: "/images/products/yellow-roses/yellow-roses-set-flatlay.jpg",
    inStock: true,
    featured: true,
    materials: ["Polymer Clay", "Sterling Silver", "Crystal Beads", "Semi-precious Stones"],
    dimensions: "Necklace: 42cm. Ring: adjustable. Earrings: 1.5cm studs",
    careInstructions: "Store each piece separately. Avoid perfumes and moisture.",
    collection: { _id: "col-4", name: "Yellow Roses", slug: { current: "yellow-roses" } },
  },
  {
    _id: "yr-2",
    name: "Yellow Rose Stud Earrings",
    slug: { current: "yellow-rose-stud-earrings" },
    description: [],
    price: 28,
    images: [],
    imageUrl: "/images/products/yellow-roses/yellow-roses-model-detail.jpg",
    inStock: true,
    materials: ["Polymer Clay", "Sterling Silver Posts"],
    dimensions: "1.5cm diameter",
    careInstructions: "Remove before sleeping. Store in provided pouch.",
    collection: { _id: "col-4", name: "Yellow Roses", slug: { current: "yellow-roses" } },
  },
  {
    _id: "yr-3",
    name: "Yellow Rose Bouquet Necklace",
    slug: { current: "yellow-rose-bouquet-necklace" },
    description: [],
    price: 65,
    images: [],
    imageUrl: "/images/products/yellow-roses/yellow-roses-necklace-closeup.jpg",
    inStock: true,
    materials: ["Polymer Clay Roses", "Sterling Silver Chain", "Agate Beads", "Crystal Beads"],
    dimensions: "42cm chain with 5cm extension, pendant cluster 6cm wide",
    careInstructions: "Handle the floral cluster gently. Store flat.",
    collection: { _id: "col-4", name: "Yellow Roses", slug: { current: "yellow-roses" } },
  },

  // === ORCHID DREAMS ===
  {
    _id: "od-1",
    name: "Violet Orchid & Agate Collection",
    slug: { current: "violet-orchid-agate-collection" },
    description: [],
    price: 110,
    images: [],
    imageUrl: "/images/products/orchid-dreams/orchid-violet-collection.jpg",
    inStock: true,
    featured: true,
    materials: ["Polymer Clay Orchids", "Sterling Silver", "Purple Agate", "Green Agate", "Crystal Beads"],
    dimensions: "Necklace: 42cm. Earrings available in agate or orchid style",
    careInstructions: "Natural agate stones may vary in pattern. Handle with care.",
    collection: { _id: "col-5", name: "Orchid Dreams", slug: { current: "orchid-dreams" } },
  },
  {
    _id: "od-2",
    name: "Orchid Bouquet Necklace",
    slug: { current: "orchid-bouquet-necklace" },
    description: [],
    price: 75,
    images: [],
    imageUrl: "/images/products/orchid-dreams/orchid-necklace-agate-display.jpg",
    inStock: true,
    materials: ["Polymer Clay Orchids & Roses", "Sterling Silver Chain", "Crystal Beads"],
    dimensions: "42cm chain with 5cm extension, pendant cluster 7cm wide",
    careInstructions: "Store flat in provided box. Avoid contact with water.",
    collection: { _id: "col-5", name: "Orchid Dreams", slug: { current: "orchid-dreams" } },
  },

  // === DARK BLOOM ===
  {
    _id: "db-1",
    name: "Dark Bloom Flower Earrings - Green",
    slug: { current: "dark-bloom-earrings-green" },
    description: [],
    price: 32,
    images: [],
    imageUrl: "/images/products/dark-bloom/dark-bloom-set-flatlay.jpg",
    inStock: true,
    materials: ["Polymer Clay", "Sterling Silver Hooks"],
    dimensions: "3cm diameter per flower",
    careInstructions: "Store in provided box. Avoid moisture.",
    collection: { _id: "col-6", name: "Dark Bloom", slug: { current: "dark-bloom" } },
  },
  {
    _id: "db-2",
    name: "Black Rose Pendant Necklace",
    slug: { current: "black-rose-pendant-necklace" },
    description: [],
    price: 45,
    images: [],
    imageUrl: "/images/products/dark-bloom/dark-bloom-set-detail.jpg",
    inStock: true,
    materials: ["Polymer Clay", "Sterling Silver Chain"],
    dimensions: "45cm chain, 3cm pendant",
    careInstructions: "Store flat. Handle pendant with care.",
    collection: { _id: "col-6", name: "Dark Bloom", slug: { current: "dark-bloom" } },
  },

  // === PINK ROSES ===
  {
    _id: "pr-1",
    name: "Pink Rose Bracelet",
    slug: { current: "pink-rose-bracelet" },
    description: [],
    price: 55,
    images: [],
    imageUrl: "/images/products/pink-roses/pink-roses-bracelet-wrist.jpg",
    inStock: true,
    materials: ["Polymer Clay Roses", "Sterling Silver Chain", "Crystal Beads"],
    dimensions: "18cm with adjustable clasp",
    careInstructions: "Remove before sleeping. Avoid water contact.",
    collection: { _id: "col-3", name: "Pink Roses", slug: { current: "pink-roses" } },
  },
  {
    _id: "pr-2",
    name: "Pink Rose Complete Beach Set",
    slug: { current: "pink-rose-beach-set" },
    description: [],
    price: 120,
    compareAtPrice: 150,
    images: [],
    imageUrl: "/images/products/pink-roses/pink-roses-full-set-beach.jpg",
    inStock: true,
    featured: true,
    materials: ["Polymer Clay Roses", "Sterling Silver", "Crystal Beads", "Semi-precious Stones"],
    dimensions: "Necklace: 42cm. Bracelet: 18cm. Earrings: 2cm studs",
    careInstructions: "Store each piece separately in provided box.",
    collection: { _id: "col-3", name: "Pink Roses", slug: { current: "pink-roses" } },
  },

  // === RED ROSES ===
  {
    _id: "rr-1",
    name: "Red Rose Bracelet & Ring Set",
    slug: { current: "red-rose-bracelet-ring-set" },
    description: [],
    price: 75,
    images: [],
    imageUrl: "/images/products/red-roses/red-roses-bracelet-ring-detail.jpg",
    inStock: true,
    materials: ["Polymer Clay Roses", "Sterling Silver", "Crystal Beads"],
    dimensions: "Bracelet: 18cm. Ring: adjustable. Earrings: 1.5cm",
    careInstructions: "Handle roses gently. Store in box.",
    collection: { _id: "col-2", name: "Red Roses", slug: { current: "red-roses" } },
  },

  // === PEONY DELICATES ===
  {
    _id: "pd-1",
    name: "Peony Crystal Stud Earrings",
    slug: { current: "peony-crystal-studs" },
    description: [],
    price: 30,
    images: [],
    imageUrl: "/images/products/peony-delicates/peony-crystal-studs-card.jpg",
    inStock: true,
    materials: ["Polymer Clay Peonies", "Sterling Silver Posts", "Swarovski Crystals"],
    dimensions: "2cm diameter",
    careInstructions: "Delicate shimmer finish. Avoid water and perfumes.",
    collection: { _id: "col-7", name: "Peony Delicates", slug: { current: "peony-delicates" } },
  },

  // === MEDITERRANEAN GARDEN ===
  {
    _id: "mg-1",
    name: "Lavender Garden Necklace & Earring Set",
    slug: { current: "lavender-garden-set" },
    description: [],
    price: 95,
    images: [],
    imageUrl: "/images/products/mediterranean-garden/lavender-brown-set-fabric.jpg",
    inStock: true,
    materials: ["Polymer Clay Roses", "Sterling Silver", "Amethyst Beads", "Crystal Beads"],
    dimensions: "Necklace: 42cm + 5cm extension. Earrings: 2.5cm studs",
    careInstructions: "Store flat in provided box. Natural stones may vary.",
    collection: { _id: "col-8", name: "Mediterranean Garden", slug: { current: "mediterranean-garden" } },
  },

  // === STUD EARRINGS ===
  {
    _id: "se-1",
    name: "Mini Bouquet Stud Earrings",
    slug: { current: "mini-bouquet-studs" },
    description: [],
    price: 25,
    images: [],
    imageUrl: "/images/products/stud-earrings/stud-earrings-trio-cards.jpg",
    inStock: true,
    materials: ["Polymer Clay", "Sterling Silver Posts"],
    dimensions: "1.5cm diameter",
    careInstructions: "Remove before sleeping. Store in provided card.",
    collection: { _id: "col-9", name: "Stud Earrings", slug: { current: "stud-earrings" } },
  },
];

export const mockCollections: Collection[] = [
  {
    _id: "col-1",
    name: "Ukrainian Heritage",
    slug: { current: "ukrainian-heritage" },
    description: "Traditional Ukrainian patterns reimagined as wearable art. Vyshyvanka cross-stitch motifs, poppy flowers, and sunflowers celebrating Ukrainian culture and craftsmanship.",
    productCount: 3,
  },
  {
    _id: "col-2",
    name: "Red Roses",
    slug: { current: "red-roses" },
    description: "Bold and passionate handcrafted red rose jewellery. Each petal sculpted by hand from polymer clay, perfect for making a statement.",
    productCount: 1,
  },
  {
    _id: "col-3",
    name: "Pink Roses",
    slug: { current: "pink-roses" },
    description: "Romantic and delicate pink rose collection. Soft petals, crystal accents, and sterling silver create pieces that bloom with femininity.",
    productCount: 2,
  },
  {
    _id: "col-4",
    name: "Yellow Roses",
    slug: { current: "yellow-roses" },
    description: "Sunshine in jewellery form. Vibrant yellow roses bring joy and warmth to any outfit. Complete sets available with matching necklace, earrings, and ring.",
    productCount: 3,
  },
  {
    _id: "col-5",
    name: "Orchid Dreams",
    slug: { current: "orchid-dreams" },
    description: "Exotic orchids meet natural agate stones. Purple, teal, and violet tones create an enchanting collection inspired by tropical gardens.",
    productCount: 2,
  },
  {
    _id: "col-6",
    name: "Dark Bloom",
    slug: { current: "dark-bloom" },
    description: "Modern and bold. Black, emerald green, and royal blue flowers for those who dare to be different. Statement pieces with attitude.",
    productCount: 2,
  },
  {
    _id: "col-7",
    name: "Peony Delicates",
    slug: { current: "peony-delicates" },
    description: "Ultra-delicate peonies with shimmer finish and Swarovski crystal centers. Perfect for brides, special occasions, or adding a touch of elegance.",
    productCount: 1,
  },
  {
    _id: "col-8",
    name: "Mediterranean Garden",
    slug: { current: "mediterranean-garden" },
    description: "Mixed bouquet collections inspired by Mediterranean gardens. Lavender, roses, and wildflowers combined with amethyst and crystal beads.",
    productCount: 1,
  },
  {
    _id: "col-9",
    name: "Stud Earrings",
    slug: { current: "stud-earrings" },
    description: "Everyday elegance. Miniature flower bouquets and single blooms in stud form. Lightweight, comfortable, and endlessly charming.",
    productCount: 1,
  },
];

export const mockBlogPosts = [
  {
    _id: "blog-1",
    title: "The Art of Polymer Clay Flower Sculpting",
    slug: { current: "art-of-polymer-clay-sculpting" },
    excerpt: "Discover how each tiny petal is sculpted by hand, creating realistic flowers that last forever. A look inside Olha's creative process.",
    publishedAt: "2026-02-10",
    author: "Olha Finiv-Hoshovska",
  },
  {
    _id: "blog-2",
    title: "Caring for Your Handcrafted Jewellery",
    slug: { current: "caring-for-handcrafted-jewellery" },
    excerpt: "Essential tips to keep your polymer clay flower jewellery looking beautiful for years. From storage to cleaning, everything you need to know.",
    publishedAt: "2026-02-05",
    author: "Olha Finiv-Hoshovska",
  },
  {
    _id: "blog-3",
    title: "Ukrainian Heritage: The Story Behind Vyshyvanka Earrings",
    slug: { current: "ukrainian-heritage-vyshyvanka-story" },
    excerpt: "How traditional Ukrainian cross-stitch patterns inspired a unique line of wearable art that connects heritage with modern fashion.",
    publishedAt: "2026-01-28",
    author: "Olha Finiv-Hoshovska",
  },
];
