import type { Product, Collection } from "./types";

// Mock product images from Unsplash
const productImages = [
  "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80",
  "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
  "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80",
  "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80",
  "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800&q=80",
  "https://images.unsplash.com/photo-1610292677835-5d11e8614d1d?w=800&q=80",
  "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&q=80",
  "https://images.unsplash.com/photo-1588444850820-a7c6da8e65c0?w=800&q=80",
];

export const mockProducts: Product[] = [
  {
    _id: "1",
    name: "Blossom Petal Earrings",
    slug: { current: "blossom-petal-earrings" },
    description: [],
    price: 45,
    compareAtPrice: 60,
    images: [],
    imageUrl: productImages[0],
    inStock: true,
    featured: true,
    materials: ["Sterling Silver", "Resin", "Natural Flowers"],
    dimensions: "2.5cm x 1.5cm",
    careInstructions: "Avoid water and direct sunlight. Store in provided box.",
  },
  {
    _id: "2",
    name: "Botanical Ring",
    slug: { current: "botanical-ring" },
    description: [],
    price: 55,
    images: [],
    imageUrl: productImages[2],
    inStock: true,
    featured: true,
    materials: ["Sterling Silver", "Real Flowers", "Eco-Resin"],
    dimensions: "Adjustable band",
    careInstructions: "Keep dry and away from chemicals.",
  },
  {
    _id: "3",
    name: "Wildflower Necklace",
    slug: { current: "wildflower-necklace" },
    description: [],
    price: 75,
    compareAtPrice: 95,
    images: [],
    imageUrl: productImages[1],
    inStock: true,
    featured: true,
    materials: ["Sterling Silver Chain", "Pressed Flowers", "Resin Pendant"],
    dimensions: "45cm chain with 5cm extension",
    careInstructions: "Wipe gently with soft cloth. Avoid moisture.",
  },
  {
    _id: "4",
    name: "Garden Rose Studs",
    slug: { current: "garden-rose-studs" },
    description: [],
    price: 38,
    images: [],
    imageUrl: productImages[3],
    inStock: true,
    featured: true,
    materials: ["Sterling Silver", "Rose Petals", "Resin"],
    dimensions: "1cm diameter",
    careInstructions: "Remove before showering or swimming.",
  },
  {
    _id: "5",
    name: "Lavender Charm Bracelet",
    slug: { current: "lavender-charm-bracelet" },
    description: [],
    price: 65,
    images: [],
    imageUrl: productImages[4],
    inStock: true,
    materials: ["Sterling Silver", "Dried Lavender", "Resin Charms"],
    dimensions: "18cm with adjustable clasp",
  },
  {
    _id: "6",
    name: "Daisy Drop Earrings",
    slug: { current: "daisy-drop-earrings" },
    description: [],
    price: 52,
    images: [],
    imageUrl: productImages[5],
    inStock: true,
    materials: ["Sterling Silver", "Real Daisies", "Eco-Resin"],
    dimensions: "3cm length",
  },
  {
    _id: "7",
    name: "Forget-Me-Not Ring",
    slug: { current: "forget-me-not-ring" },
    description: [],
    price: 48,
    images: [],
    imageUrl: productImages[6],
    inStock: false,
    materials: ["Sterling Silver", "Forget-Me-Not Flowers", "Resin"],
    dimensions: "Adjustable",
  },
  {
    _id: "8",
    name: "Cherry Blossom Pendant",
    slug: { current: "cherry-blossom-pendant" },
    description: [],
    price: 68,
    images: [],
    imageUrl: productImages[7],
    inStock: true,
    materials: ["Sterling Silver", "Cherry Blossoms", "Resin"],
    dimensions: "50cm chain, 2cm pendant",
  },
];

export const mockCollections: Collection[] = [
  {
    _id: "col-1",
    name: "Floral Earrings",
    slug: { current: "floral-earrings" },
    description: "Delicate earrings featuring real pressed flowers",
    productCount: 12,
  },
  {
    _id: "col-2",
    name: "Botanical Necklaces",
    slug: { current: "botanical-necklaces" },
    description: "Nature-inspired pendants with preserved botanicals",
    productCount: 8,
  },
  {
    _id: "col-3",
    name: "Garden Rings",
    slug: { current: "garden-rings" },
    description: "Adjustable rings with miniature floral gardens",
    productCount: 15,
  },
];

export const mockBlogPosts = [
  {
    _id: "blog-1",
    title: "The Art of Preserving Flowers in Resin",
    slug: { current: "art-of-preserving-flowers" },
    excerpt: "Discover the delicate process behind each handcrafted piece and how we capture nature's beauty forever.",
    publishedAt: "2026-02-10",
    author: "Olha Blossom",
  },
  {
    _id: "blog-2",
    title: "Caring for Your Botanical Jewellery",
    slug: { current: "caring-for-botanical-jewellery" },
    excerpt: "Essential tips to keep your nature-inspired pieces looking beautiful for years to come.",
    publishedAt: "2026-02-05",
    author: "Olha Blossom",
  },
  {
    _id: "blog-3",
    title: "Spring Collection: Cherry Blossoms",
    slug: { current: "spring-collection-cherry-blossoms" },
    excerpt: "Introducing our new spring collection featuring delicate cherry blossom petals from European gardens.",
    publishedAt: "2026-01-28",
    author: "Olha Blossom",
  },
];
